import numpy as np
arr=np.array([1,2,3,4],np.int8)
print(arr)
print(arr.dtype)
arr[1]=99
print(arr)
listarr=np.array([[12,34,123,234],[56,78,90,12]],np.int16)
print(listarr)
print(listarr.dtype)
print(listarr.shape)
print(listarr.size)
arr1=np.array({12,23,34,45,56})
print(arr1.dtype)
zeroes=np.zeros((2,3))
print(zeroes)
rng=np.arange(10,50,5)
print(rng)
lspace=np.linspace(1,10,4)
print(lspace)
print("i am in empty")
emp=np.empty((2,3))
print(emp)
print("i am in empty as i want: ")
emp1=np.empty_like(lspace)
print(emp1)
id=np.identity(3)
print(id)
print(id.shape)

arr2=np.arange(5, 45)
print(arr2)
print("reshaping the array")
arr2.resize((3,15))
print(arr2)